<?php
//Main
$language_basic = array( 
	'A' 					=> '個',
	'Please' 				=> '請', 
	'Year' 					=> '年', 
	'Day' 					=> '天', 
	'Hour' 					=> '小時', 
	'Minute' 				=> '分鐘', 
	'Jooyea' 				=> '聚易', 
	'Friend' 				=> '好友', 
	'Online' 				=> '在線', 
	'Busy' 					=> '忙碌', 
	'Leave' 				=> '離開', 
	'Hiding' 				=> '隱身', 
	'Offline' 				=> '離線', 
	'Manage' 				=> '管理', 
	'Setting' 				=> '設置', 
	'Confirm' 				=> '確定', 
	'Successfully' 			=> '成功！ ', 
	'Failed' 				=> '失敗！ ', 
	'Out' 					=> '退出', 
	'Close' 				=> '關閉', 
	'Cancel' 				=> '取消', 
	'Delete' 				=> '刪除', 
	'Modify' 				=> '修改', 
	'Select' 				=> '選擇', 
	'Msg'					=>	'消息',
	'Ellipsis' 				=> '...', 
	'Move' 					=> '移動>>', 
	'Min' 					=> '最小化', 
	'Stranger' 				=> '陌生人', 
	'DiscussionGroup' 		=> '討論組', 
	'OnlineFriend' 			=> '在線好友', 
	'SearchFriend' 			=> '搜索好友', 
	'userico' 				=> '用戶頭像', 
	'CloseContacted' 		=> '最近聯繫人', 
	'SysSetting' 			=> '系統設置', 
	'BasicSetting' 			=> '基本設置', 
	'Anticlutter' 			=> '安全隱私', 
	'updateMood' 			=> '編輯心情', 
	'FriendsList' 			=> '好友列表', 
	'UploadUserIco' 		=> '上傳頭像', 
	'ClickForDownload' 		=> '點擊下載', 
	'OnlineTime' 			=> '在線時間：', 
	'MyFriend' 				=> '我的好友', 
	'AvatarSetting' 		=> '頭像設置', 
	'YouHaveNewMsg' 		=> '您有新消息', 
	'FileIsNotExist' 		=> '文件不存在！ ', 
	'SelectUploadFile' 		=> '選擇上傳文件', 
	'PlayAudio' 			=> '開啟聲音提示', 
	'InputName' 			=> '請輸入好友姓名', 
	'LanguageChange' 		=> '切換到簡體中文', 
	'CannotFindFriend' 		=> '沒有找到匹配的好友',
);

//在线状态
$language_online = array(
	'0'						=>	'在線',
	'1'						=>	'在線',
	'2'						=>	'隱身',
	'3'						=>	'忙碌',
	'4'						=>	'離開',
);

//好友
$language_friend = array(
	'DelGroupWarning' 		=> "選定的分組將被刪除，組內的好友將被移動到系統默認分組“我的好友”。 \r\n您確定要刪除該分組嗎？ ",
	'DelFriendWarning'	 	=> "刪除好友將一併刪除與此好友的聊天記錄！ \r\n確認刪除？ ",
	'InputGroupName' 		=> '請輸入分組名稱！ ',
	'AddNewGroup' 			=> '創建新分組',
	'Group' 				=> '分組',
	'SearchUser' 			=> '查找聯繫人',
	'Search'				=>	'查 找',	
);

//聊天窗口
$language_talkwin = array(
	'Invite'				=>	'邀請',
	'Report'				=>	'舉報',
	'ClearWindow'			=>	'清屏',
	'SearchFace'			=>	'選擇表情',
	'FileTransfer'			=>	'文件傳輸',
	'Send'					=>	'發送',
	'LastWord'				=>	'剩餘字數：',
	'Record'				=>	'聊天記錄',
	'PreviousPage'			=>	'上一頁',
	'NextPage'				=>	'下一頁',
	'NowPage'				=>	'第',
	'Page'					=>	'頁',
	'PageSum'				=>	'總共',
	'PleaseSelect'			=>	'請選擇',
	'NowPageSelect' 		=> 	'當前頁',
	'Whole'					=>	'全部',
	'Annal' 				=> 	'記錄',
	'DeleteThisRecord'	 	=> 	'刪除本條記錄',
	'ConfirmDel' 			=> 	'確定刪除？ ',
	'BecomeFriend'			=>	'加為好友',
	'NowTransferFile'		=>	'正在傳送文件: ',
	'AddFriendSuccessfully'	=>	'已成功加為好友',
	'AddFriendFailed'		=>	'加為好友失敗',
	'RefuseToBeFriend'		=>	'對方拒絕任何人加為好友！',
	'HasBeenInFriendList'	=>	'已在您的好友列表裏',	
	'WrongAnswer'	 		=> 	'答案錯誤！ ',
	'NeedToAnswerQuestion' 	=> 	'對方需要您回答一下驗證問題：',
	'InputTheAnswer' 		=> 	'請輸入問題答案！ ',
	'SystemNotice'			=>	'【系統提示】',
	'Loading'				=>	'正在加載，請稍候。。。',
	'NoChattingRecord'		=>	'無聊天記錄！',
	'Video' 				=> 	'視頻',
	'TransferImg' 			=> 	'發送圖片',
	'MessageRecord' 		=> 	'消息記錄',
	'GooupInfo' 			=> 	'群信息',
	'TalkGroupMember' 		=> 	'討論組成員',
	'VideoIsCanceled' 		=> 	'視頻請求已取消！ ',
	'VideoContacted' 		=> 	'視頻連接成功！ ',
	'PostEnter' 			=> 	'按Enter鍵發送消息',
	'PostCtrlEnter' 		=> 	'按Ctrl+Enter鍵發送消息',
	'PostAltS' 				=> 	'按Alt+S鍵發送消息',
);

//討論組
$language_group = array(
	'CreateGroup'			=>	'創建組',
	'CreateTalkGroup'		=>	'創建討論組',
	'SearchGroup'			=>	'查找組',
	'SearchTalkGroup'		=>	'查找討論組',
	'MyGroup'				=>	'我創建的討論組',
	'MyOtherGroup'			=>	'我加入的討論組',
	'GroupName'				=>	'討論組名稱：',
	'InsertGroupName'		=>	'請輸入您要創建的討論組的名稱',
	'GroupWarn'				=>	'<p><b>創建討論組注意事項：</b></p><p>一個討論組最多人數限制30人。</p><p>創建成功後的討論組可以通過討論組管理進行管理。</p><p>請不要創建重複的討論組。</p>',
	'GroupIsFull'			=>	'[討論組滿員]',
	'NoMyGroup'				=>	'沒有我創建的討論組！',
	'NoMyOtherGroup'		=>	'没有我所加入的討論組！',
	'Dismiss'				=>	'解散',
	'Manage'				=>	'管理',
	'Out'					=>	'退出',
	'Application' 			=> 	'申請',
	'Already' 				=> 	'已經',
	'JoinIn' 				=> 	'加入',
	'People'				=>	'人',
	'MemberManage'			=>	'成員管理',
	'MemberRestraint'		=>	'添加成員不能超過30人',
	'MemberEditSuccessfully'=>	'討論組成員編輯成功！',
	'OutGroupSuccessfully'	=>	'您已成功退出討論組！',
	'ReenterGroupName'		=>	'請重新輸入要查找的討論組！ ',
	'NotFoundGroup' 		=> 	'沒有找到相關的討論組！',
);

//安全隱私 
$language_limit = array( 
	'AllowAnyBody' 			=> 	'允許任何人加我為好友', 
	'NeedQuestion' 			=> 	'需要回答問題', 
	'Question' 				=> 	'問題', 
	'Answer' 				=> 	'答案', 
	'RefuseAnyBody' 		=> 	'禁止任何人加我為好友' 
);

//表情
$language_face = array(
	'Smile'					=>	'微笑',
	'Grin'					=>	'呲牙笑',
	'Titter'				=>	'偷笑',
	'OutTongue'				=>	'吐舌',
	'BadSmile'				=>	'色迷迷',
	'Ashamed'				=>	'害羞',
	'Cool'					=>	'耍酷',
	'Dizzy'					=>	'暈',
	'Doubt'					=>	'疑惑',
	'Sweat'					=>	'流汗',
	'Sad'					=>	'難過',
	'Dissatisfied'			=>	'不滿',
	'Amazed'				=>	'吃驚',
	'NotUnderstand'			=>	'不明白',
	'Angry'					=>	'生氣',
	'Anger'					=>	'暴怒',
	'Sleeping'				=>	'睡覺',
	'ShutUp'				=>	'閉嘴',
	'Weak'					=>	'衰',
	'Pig'					=>	'豬頭',
	'Heart'					=>	'紅心',
	'HeartCold' 			=> 	'心碎',
	'Flower'				=>	'鮮花',
	'Wither'				=>	'凋謝',
	'Goodnight'				=>	'晚安',
	'Knock'					=>	'拍磚',
	'Money'					=>	'金錢',
	'Feces'					=>	'便便',
	'Vomit'					=>	'嘔吐',
	'Baste'					=>	'扁你',
	'Good'					=>	'好',
	'Applause'				=>	'鼓掌',
	'Support'				=>	'支持你',
	'Despise'				=>	'鄙視你',
	'Surrender'				=>	'投降',
	'Winner'				=>	'勝利',
	'OK'					=>	'OK',
	'Handshake'				=>	'握手',
	'Hug'					=>	'抱抱',
	'Pump'					=>	'抽你',
	'Kiss'					=>	'親一個',
	'Grievance'				=>	'委屈',
	'Wail'					=>	'痛哭',
	'Exclaim'				=>	'驚叫',
	'Mad'					=>	'抓狂',
	'Thurification'			=>	'燒香',
	'Expectation'			=>	'期望',
	'Talk'					=>	'喊話',
	'Invigorating'			=>	'爽歪歪',
);

//文件傳輸
$language_transfer = array(
	'FileNotExist' 			=> '文件不存在',
	'OutRestraint' 			=> '文件大小超過了服務器限制',
	'TransferFailed' 		=> '文件傳輸失敗！ ',
	'UnknowType' 			=> '文件類型不符合，允許上傳的文件類型是：',
	'PermitFileType' 		=> '服務器不允許傳輸此類文件！ ',
	'FileUpdateToServer' 	=> '文件已成功上傳至服務器',
	'TransferFileOff' 		=> '服務器暫不支持文件傳輸',
);